### ISSUE TITLE
The startup_crew.py didn't find the openai key

### ISSUE THREAD

**Issue by kabelklaus** [majacinka/crewai-experiments#7]
Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)

# To Load GPT-4
api = os.environ.get("sk-proj-fNk......")

**Comment by nicikiefer** [comment]
@kabelklaus please don't expect anyone to post their OpenAI API key online. This is meant as a placeholder so you know where you put yours.

**Comment by kabelklaus** [comment]
> @kabelklaus please don't expect anyone to post their OpenAI API key online. This is meant as a placeholder so you know where you put yours.

Please read before you write.
Nobody expect a api key.

**Comment by nicikiefer** [comment]
> Did not find openai_api_key, please add an environment variable OPENAI_API_KEY which contains it

You are correct. I understood that you are requesting the addition of the environment variable that contains the key as well. But it seems like you were pointing out to use an environment variable instead of the key in string form.

> Please read before you write.
Nobody expect a api key.

Your comment would have been more helpful if you would hint at what exactly you mean. That would increase the chance of other people making contributions in your favor.
